[package]
name = "cpu-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
user-lib = { path = "../user-lib" }
gag = "1.0.0"
